layout_spectrum: 0.936231
typography_spectrum: 0.04503068
color:
  saturation: 0.5334113
  lightness: 0.211555
  brandStrength: 0.3906432
  rhythmicContrast: 0.7750051
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Kajakbilen
